

export const initialValues = {
    emailChecked: false,
    firstName: '',
    middleName: "",
    lastName: '',
    contactNumber: '',
    alternateContactNumber: '',
    emailID: '',
    dateOfBirth: '',
    age: '',
    gender: '',
    maritalStatus: '',
    nationality: "",
    bloodGroup: '',
    currentResidentialAddress: '',
    permanentResidentialAddress: '',
    currentLocation: '',
    preferredLocation: '',
    passport: '',
    passportNumber: '',
    passportCopy: '',
    adhaarCardNumber: '',
    adharCardCopy: '',
    panCardNumber: '',
    panCardCopy: '',
    drivingLicenseDetails: '',
    drivingLicenseCopy: '',
    voterIdDetails: '',
    voterIdCopy: '',
    photograph: '',
    linkedIn: '',
    resume: '',
    socialLinks: '',
    onlinePortfolioLink: '',
    skills: '',
    languagesKnown: '',
    educationCourse: '',
    specialization: '',
    educationInstitution: '',
    yearOfCompletion: '',
    passPercentage: '',
    proofOfEducationCompletion: '',
    anyCertifications: '',
    certificationsObtained: '',
    certificationIssuingAuthority: '',
    certificationCompletionDate: '',
    proofOfCertification: '',
    dateOfJoin: '',
    fresher: '',

    totalExperience: 'N/A',
    organizationName: 'N/A',
    jobTitle: 'N/A',
    empStartDate: 'N/A',
    empEndDate: 'N/A',
    rolesAndResponsibilities: 'N/A',
    reasonForLeaving: 'N/A',
    currentCTC: 'N/A',
    expectedCTC: 'N/A',
    noticePeriod: 'N/A',
    salarySlips: 'N/A',
    bankStatements: 'N/A',
    offerLetter: 'N/A',
    incrementLetter: 'N/A',
    experienceCertificate: 'N/A',
    servingNoticePeriod: 'N/A',
    lastWorkingDate: 'N/A',
    anyExistingOffers: 'N/A',
    existingOfferOrganizationName: 'N/A',
    proofOfExistingOffer: 'N/A',
    haveYouAcceptedTheOffer: 'N/A',
    dateAcceptedTheOffer: 'N/A',
    proposedCTC: 'N/A',
    referenceContactPersonName: 'N/A',
    referenceContactPersonDesignation: 'N/A',
    referenceContactPersonContact: 'N/A',
    referenceContactPersonEmailID: 'N/A',
    referenceContactPersonProfessionalRelationship: 'N/A',
    referenceCheckDate: 'N/A',
    employmentVerificationConsent: 'N/A',
    authorizationToContactReferences: 'N/A',
    backgroundChecks: '',
    drugAndAlcoholTest: '',
    criminalCases: '',
    detailsOfCriminalCases: '',
    acknowledge: '',


}





