

export const initialValues = {
    emailChecked: false,
    firstName: '',
    middleName: "",
    lastName: '',
    contactNumber: '',
    alternateContactNumber: '',
    emailID: '',
    dateOfBirth: '',
    age: '',
    gender: '',
    maritalStatus: '',
    nationality: "",
    bloodGroup: '',
    currentResidentialAddress: '',
    permanentResidentialAddress: '',
    currentLocation: '',
    preferredLocation: '',
    passport: '',
    passportNumber: '',
    passportCopy: '',
    adhaarCardNumber: '',
    adharCardCopy: '',
    panCardNumber: '',
    panCardCopy: '',
    drivingLicenseDetails: '',
    drivingLicenseCopy: '',
    voterIdDetails: '',
    voterIdCopy: '',
    photograph: '',
    linkedIn: '',
    resume: '',
    socialLinks: '',
    onlinePortfolioLink: '',
    skills: '',
    languagesKnown: '',
    educationCourse: '',
    specialization: '',
    educationInstitution: '',
    yearOfCompletion: '',
    passPercentage: '',
    proofOfEducationCompletion: '',
    anyCertifications: '',
    certificationsObtained: '',
    certificationIssuingAuthority: '',
    certificationCompletionDate: '',
    proofOfCertification: '',
    dateOfJoin: '',
    fresher: '',
    totalExperience : '',
    organizationName : '',
    jobTitle : '',
    empStartDate : '',
    empEndDate : '',
    rolesAndResponsibilities : '',
    reasonForLeaving : '',
    currentCTC: '',
    expectedCTC: '',
    noticePeriod: '',
    salarySlips : '',
    bankStatements : '',
    offerLetter: '',
    incrementLetter: '',
    experienceCertificate : '',
    servingNoticePeriod : '',
    lastWorkingDate : '',
    anyExistingOffers : '',
    existingOfferOrganizationName : '',
    proofOfExistingOffer : '',
    haveYouAcceptedTheOffer : '',
    dateAcceptedTheOffer : '',
    proposedCTC : '',
    referenceContactPersonName : '',
    referenceContactPersonDesignation : '',
    referenceContactPersonContact : '',
    referenceContactPersonEmailID : '',
    referenceContactPersonProfessionalRelationship : '',
    referenceCheckDate : '',
    employmentVerificationConsent: '',
    authorizationToContactReferences: '',
    backgroundChecks: '',
    drugAndAlcoholTest: '',
    criminalCases: '',
    detailsOfCriminalCases: '',
    acknowledge: '',


}





