
export const initialValues = {
    emailChecked: false,
    firstName: '',
    middleName: "",
    lastName: '',
    contactNumber: '',
    alternateContactNumber: '',
    emailID: '',
    dateOfBirth: '',
    age: '',
    gender: '',
    maritalStatus: '',
    nationality: "",
    bloodGroup: '',
    currentResidentialAddress: '',
    permanentResidentialAddress: '',
    currentLocation: '',
    preferredLocation: '',
    passport: '',
    passportNumber: '',
    passportCopy: '',
    adhaarCardNumber: '',
    adharCardCopy: '',
    panCardNumber: '',
    panCardCopy: '',
    drivingLicenseDetails: '',
    drivingLicenseCopy: '',
    voterIdDetails: '',
    voterIdCopy: '',
    photograph: '',
    linkedIn: '',
    resume: '',
    socialLinks: '',
    onlinePortfolioLink: '',
    skills: '',
    languagesKnown: '',
    educationCourse: '',
    specialization: '',
    educationInstitution: '',
    yearOfCompletion: '',
    passPercentage: '',
    proofOfEducationCompletion: '',
    anyCertifications: '',
    certificationsObtained: '',
    certificationIssuingAuthority: '',
    certificationCompletionDate: '',
    proofOfCertification: '',
    dateOfJoin: '',
    fresher: '',
    backgroundChecks: '',
    drugAndAlcoholTest: '',
    criminalCases: '',
    detailsOfCriminalCases: '',
    acknowledge: '',


}


